site_name: "Enterprise Architecture "
site_description: "A blog for IT architecture"
docs_dir: "docs"
repo_url: "https://github.com/bcgov/architect-for-bcgov"
edit_uri: edit/main/docs
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
    - git-revision-date-localized
markdown_extensions:
    - md_in_html
    -   mkpatcher:
            location: patcher.py
nav:
- Getting Started:
  - Introduction to Enterprise Architecture: index.md
- Disaster Recovery:
  - High Availability is not Disaster Recovery: resilience-design-principles.md 
- Artificial Intelligence
  - AI Development Lifecycle: AI-Development-Lifecycle.md
  - Large Language Models: 
    - Chatbots
       - Building a Chatbot in Google Cloud: ./artificial-intelligence/chatbot-gcp.md

