site_name: "BC Government IT architecture docs"
site_description: "A guide to IT architecture in the BC government."
docs_dir: "docs"
plugins:
    - techdocs-core
markdown_extensions:
    - md_in_html
    -   mkpatcher:
            location: patcher.py
nav:
- Getting Started:
  - Introduction to Enterprise Architecture: index.md
- Disaster Recovery:
  - High Availability is not Disaster Recovery: resilience-design-principles.md 
- Artificial Intelligence
  - Large Language Models: 
    - Chatbots
       - Building a Chatbot in Google Cloud: ./artificial-intelligence/chatbot-gcp.md
