site_name: "BC Government IT architecture docs"
site_description: "A guide to IT architecture in the BC government."
docs_dir: "docs"
plugins:
    - techdocs-core
markdown_extensions:
    - md_in_html
    -   mkpatcher:
            location: patcher.py
