site_name: "BC Government IT architecture docs"
site_description: "A guide to IT architecture in the BC government."
docs_dir: "docs"
plugins:
    - techdocs-core
markdown_extensions:
    - md_in_html
    -   mkpatcher:
            location: patcher.py
nav:
- Getting Started:
  - Introduction to Enterprise Architecture: index.md
- Disaster Recovery:
  - High Availability is not Disaster Recovery: resilience-design-principles.md 
- Everything Cloud:
  - Data and AI:
    - The Data Assembly Line: ./everything-cloud/data-and-ai/data-assembly.md
    - Data Storage Options: ./everything-cloud/data-and-ai/data-storage.md
    - Data Analysis: ./everything-cloud/data-and-ai/data-analysis.md
    - AI Terminology : ./everything-cloud/data-and-ai/ai-terminology.md
